// <auto-generated />
namespace EventsManager.Web.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddEntitiesDomain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEntitiesDomain));
        
        string IMigrationMetadata.Id
        {
            get { return "201802040428409_AddEntitiesDomain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
